const FISCAL_URL=Deno.env.get('SUPABASE_URL')!;const FISCAL_SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const prevFiscalServe=Deno.serve.bind(Deno);
function fClean(v:unknown){return String(v??'').trim();}function fNorm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}function fDigits(v:unknown){return String(v??'').replace(/\D/g,'');}
function fiscalIntent(text:string){const t=fNorm(text);return /\b(nf-?e|nfe|nota fiscal|danfe|xml da nota|chave de acesso)\b/.test(t)||/\b(nota)\b.{0,25}\b(fiscal|emitida|emitir|emissao)\b/.test(t);}
function requestIntent(text:string){const t=fNorm(text);return /\b(quero|preciso|pode|consegue|emitir|emite|gerar|gera|mandar|manda|enviar|envia|solicitar|solicita)\b.{0,30}\b(nf-?e|nfe|nota fiscal|danfe|xml)\b/.test(t)||/\b(nf-?e|nfe|nota fiscal)\b.{0,30}\b(quero|preciso|emitir|gerar|mandar|enviar)\b/.test(t);}
function orderNo(text:string){const m=text.match(/(?:pedido|venda|n[º°o]?|#)\s*[:#-]?\s*(\d{1,9})/i);return m?.[1]??null;}
async function fCall(phone:string,action:string,numero:string|null){try{const r=await fetch(`${FISCAL_URL}/functions/v1/joao-erp-fiscal-read`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${FISCAL_SERVICE}`},body:JSON.stringify({phone,limit:5,intent:action,action,numero_venda:numero}),signal:AbortSignal.timeout(12000)});return await r.json().catch(()=>({ok:false,code:`HTTP_${r.status}`}));}catch{return{ok:false,code:'READ_UNAVAILABLE'};}}
function choose(sales:any[],requested:string|null){if(requested)return sales.find((s:any)=>String(s?.numero_venda??'')===requested)??null;return sales.length===1?sales[0]:null;}
function statusReply(data:any,original:string){const sales=Array.isArray(data?.sales)?data.sales:[],requested=orderNo(original);if(!data?.ok||sales.length===0)return requested?`Não localizei informação fiscal do pedido ${requested} no ERP.`:'Não localizei pedido com informação fiscal no ERP para este WhatsApp.';if(!requested&&sales.length>1)return`Encontrei mais de um pedido. Qual número você quer consultar? Aqui aparecem: ${sales.map((s:any)=>s?.numero_venda).filter(Boolean).slice(0,5).join(', ')}.`;const s=choose(sales,requested);if(!s)return`Não encontrei o pedido ${requested} entre os pedidos localizados para este WhatsApp.`;const ref=s.numero_venda??'sem número',st=fNorm(fClean(s.nota_status));if(st==='autorizada')return`Pedido ${ref}: a NF-e consta autorizada no ERP${s.nota_numero?`, número ${s.nota_numero}`:''}.`;if(st==='rejeitada')return`Pedido ${ref}: a tentativa de NF-e consta rejeitada no ERP. Ainda não há NF-e autorizada para esse pedido.`;if(st==='em_processamento'||st==='pendente')return`Pedido ${ref}: a NF-e ainda está em processamento/pendente no ERP; não consta como autorizada.`;if(s.preflight_ok===true)return`Pedido ${ref}: ainda não há NF-e autorizada registrada no ERP.`;return`Pedido ${ref}: a NF-e ainda não está pronta no ERP porque existe uma pendência fiscal de configuração.`;}
async function requestReply(phone:string,data:any,original:string){const sales=Array.isArray(data?.sales)?data.sales:[],requested=orderNo(original);if(!data?.ok||sales.length===0)return{reply:requested?`Não localizei o pedido ${requested} no ERP para registrar a solicitação fiscal.`:'Não localizei um pedido no ERP para registrar a solicitação fiscal.',code:'NO_SALE'};if(!requested&&sales.length>1)return{reply:`Encontrei mais de um pedido. Qual número precisa da nota fiscal? Aqui aparecem: ${sales.map((s:any)=>s?.numero_venda).filter(Boolean).slice(0,5).join(', ')}.`,code:'AMBIGUOUS'};const s=choose(sales,requested);if(!s)return{reply:`Não encontrei o pedido ${requested} entre os pedidos localizados para este WhatsApp.`,code:'NOT_FOUND'};const r=await fCall(phone,'request',String(s.numero_venda??''));if(r?.ok&&r?.code==='FISCAL_REQUEST_READY_HOMOLOGATION')return{reply:`Registrei a solicitação fiscal do pedido ${s.numero_venda} no ERP. Ainda não há NF-e autorizada; o fluxo fiscal está em homologação.`,code:r.code};if(r?.ok&&r?.code==='FISCAL_REQUEST_PENDING_CONFIG')return{reply:`Registrei a solicitação fiscal do pedido ${s.numero_venda} no ERP. Ela ficou pendente de configuração fiscal e ainda não há NF-e autorizada.`,code:r.code};return{reply:`Não consegui registrar a solicitação fiscal do pedido ${s.numero_venda} com segurança agora.`,code:r?.code??'REQUEST_FAILED'};}
function dryFiscal(reply:string,code:any){return new Response(JSON.stringify({ok:true,respondeu:true,dry_run:true,tema:'fiscal_erp',resposta:reply,erp_read:true,code}),{status:200,headers:{'content-type':'application/json'}});}
(Deno as any).serve=(...args:any[])=>{const idx=typeof args[0]==='function'?0:1;const handler=args[idx];if(typeof handler!=='function')return(prevFiscalServe as any)(...args);args[idx]=async(req:Request,info:any)=>{if(req.method!=='POST')return handler(req,info);let body:any;try{body=await req.clone().json();}catch{return handler(req,info);}if(!body||body._sweep===true||fClean(body._direct_message))return handler(req,info);const phone=fDigits(body.phone),original=fClean(body.mensagem);if(phone.length<10||!original||!fiscalIntent(original))return handler(req,info);const data=await fCall(phone,'status',null);let reply:string,code:any=data?.code??null;if(requestIntent(original)){const rr=await requestReply(phone,data,original);reply=rr.reply;code=rr.code;}else reply=statusReply(data,original);if(body._dry_run===true)return dryFiscal(reply,code);const direct={...body,_direct_message:reply,_assinar_como:'joao',_source_tag:'joao_erp_fiscal_v1'};delete direct._dry_run;return handler(new Request(req.url,{method:req.method,headers:req.headers,body:JSON.stringify(direct)}),info);};return(prevFiscalServe as any)(...args);};
