const PAY_PRELOAD_URL=Deno.env.get('SUPABASE_URL')!;
const PAY_PRELOAD_SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const previousServePayment=Deno.serve.bind(Deno);
function pClean(v:unknown){return String(v??'').trim();}
function pNorm(v:string){return v.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
function pDigits(v:unknown){return String(v??'').replace(/\D/g,'');}
function inFlight(text:string){const t=pNorm(text);return /\b(acabei de pagar|ja paguei|paguei agora|paguei hoje|pix caiu|pix entrou|pix foi aprovado|pagamento caiu|pagamento entrou|pagamento foi aprovado|deu baixa|mandei o pix|fiz o pix|enviei (o )?comprovante|mandei (o )?comprovante|comprovante enviado)\b/.test(t);}
function paymentHistoryIntent(text:string){const t=pNorm(text);if(inFlight(text))return false;if(/\b(parcela|parcelas|vencimento|vence|vencida|vencidas)\b/.test(t))return true;if(/\b(historico|historico de pagamento|pagamentos anteriores|pagamento anterior)\b/.test(t))return true;if(/\b(saldo|quanto falta pagar|quanto ainda falta|valor em aberto|tem algo pendente|tenho algo pendente)\b/.test(t))return true;if(/\b(esta paga|ta paga|foi paga|consta pago|consta recebida|consta recebido)\b/.test(t)&&/\b(parcela|fatura|titulo|pagamento)\b/.test(t))return true;return false;}
function pKind(text:string){const t=pNorm(text);if(/histor/.test(t))return'history';if(/saldo|quanto falta|em aberto|pendente/.test(t))return'balance';if(/venc|vence/.test(t))return'due';if(/parcela/.test(t))return'parcel';return'history';}
function parcelNo(text:string){const m=pNorm(text).match(/parcela\s*(?:n[ºo]?\s*)?(\d{1,3})/);return m?Number(m[1]):null;}
function money(v:any){const n=Number(v??0);return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number.isFinite(n)?n:0);}
function dateBr(v:any){if(!v)return null;const s=String(v);const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:s;}
function itemLabel(i:any){const p=i?.parcela_atual&&i?.total_parcelas?`parcela ${i.parcela_atual}/${i.total_parcelas}`:(i?.parcela_atual?`parcela ${i.parcela_atual}`:'título');const st=pClean(i?.status)||'sem status';const due=dateBr(i?.data_vencimento);return `${p}: ${st}, ${money(i?.valor)}${due?`, vencimento ${due}`:''}`;}
function replyPayment(data:any,original:string){const items=Array.isArray(data?.items)?data.items:[];const s=data?.summary||{};const k=pKind(original);const pn=parcelNo(original);if(!data?.ok||data?.code==='NO_RECEIVABLES'||items.length===0)return 'Não encontrei parcelas ou histórico financeiro registrado no ERP para este WhatsApp.';if(pn!==null){const matches=items.filter((i:any)=>Number(i?.parcela_atual)===pn);if(matches.length===0)return `Não encontrei a parcela ${pn} entre os lançamentos financeiros retornados pelo ERP.`;if(matches.length===1){const i=matches[0];const rec=i?.status==='Recebido'?` Recebimento registrado${i?.data_recebimento?` em ${dateBr(i.data_recebimento)}`:''}, no valor de ${money(i?.valor_recebido??i?.valor)}.`:'';return `Parcela ${pn}: ${pClean(i?.status)||'sem status'} no ERP, valor ${money(i?.valor)}${i?.data_vencimento?`, vencimento ${dateBr(i.data_vencimento)}`:''}.${rec}`;}return `Encontrei mais de um lançamento como parcela ${pn}. Aqui aparecem: ${matches.slice(0,4).map(itemLabel).join('; ')}. Me diga o documento ou vencimento que você quer conferir.`;}if(k==='balance'){const c=Number(s?.open_count??0);if(c<=0)return 'O ERP não registra títulos em aberto neste momento.';return `O ERP registra ${c} título${c===1?'':'s'} em aberto, somando ${money(s?.open)}. Cancelados ficam fora dessa soma.`;}if(k==='due'){const open=items.filter((i:any)=>['Pendente','Parcial','Vencido'].includes(pClean(i?.status)));if(open.length===0)return 'O ERP não registra parcela pendente, parcial ou vencida neste momento.';return `Vencimentos em aberto no ERP: ${open.slice(0,4).map(itemLabel).join('; ')}${open.length>4?'. Há outros lançamentos além destes.':''}`;}if(k==='history')return `Histórico recente no ERP: ${items.slice(0,5).map(itemLabel).join('; ')}.`;return `No ERP constam ${Number(s?.received_count??0)} recebidos e ${Number(s?.open_count??0)} em aberto.`;}
async function readPayment(phone:string,original:string){try{const r=await fetch(`${PAY_PRELOAD_URL}/functions/v1/joao-erp-payment-read`,{method:'POST',headers:{'content-type':'application/json',Authorization:`Bearer ${PAY_PRELOAD_SERVICE}`},body:JSON.stringify({phone,limit:24,intent:pKind(original)}),signal:AbortSignal.timeout(12000)});const d=await r.json().catch(()=>null);return d||{ok:false,code:`HTTP_${r.status}`,items:[]};}catch{return{ok:false,code:'READ_UNAVAILABLE',items:[]};}}
async function readInflight(phone:string){try{const r=await fetch(`${PAY_PRELOAD_URL}/rest/v1/rpc/fn_joao_pagamento_em_curso_v1`,{method:'POST',headers:{'content-type':'application/json',apikey:PAY_PRELOAD_SERVICE,Authorization:`Bearer ${PAY_PRELOAD_SERVICE}`},body:JSON.stringify({p_phone:phone}),signal:AbortSignal.timeout(8000)});const d=await r.json().catch(()=>null);return d||{ok:false,code:`HTTP_${r.status}`};}catch{return{ok:false,code:'READ_UNAVAILABLE'};}}
function replyInflight(data:any){const code=pClean(data?.code);if(code==='PAYMENT_APPROVED')return `Sim. O Córtex registra o PIX de ${money(data?.valor)} como aprovado${data?.paid_at?` em ${new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(data.paid_at))}`:''}.`;if(code==='PAYMENT_PENDING')return `Neste momento, a cobrança mais recente aparece como pendente no Córtex${data?.valor!=null?`, no valor de ${money(data.valor)}`:''}. Ainda não vou marcar como paga sem a confirmação automática.`;if(code==='PAYMENT_CANCELLED')return `A cobrança mais recente aparece como cancelada no Córtex${data?.valor!=null?`, no valor de ${money(data.valor)}`:''}; não consta como aprovada.`;return 'Ainda não tenho confirmação automática desse pagamento no Córtex. Não vou marcar como pago sem uma baixa confiável.';}
function dryPayment(reply:string,data:any,tema='consulta_pagamento_erp'){return new Response(JSON.stringify({ok:true,respondeu:true,dry_run:true,tema,resposta:reply,erp_read:tema==='consulta_pagamento_erp',cortex_read:tema==='consulta_pagamento_cortex',code:data?.code??null,version:data?.version??null}),{status:200,headers:{'content-type':'application/json'}});}
(Deno as any).serve=(...args:any[])=>{const idx=typeof args[0]==='function'?0:1;const handler=args[idx];if(typeof handler!=='function')return(previousServePayment as any)(...args);args[idx]=async(req:Request,info:any)=>{if(req.method!=='POST')return handler(req,info);let body:any;try{body=await req.clone().json();}catch{return handler(req,info);}if(!body||body._sweep===true||pClean(body._direct_message))return handler(req,info);const phone=pDigits(body.phone),original=pClean(body.mensagem);if(phone.length<10||!original)return handler(req,info);if(inFlight(original)){const data=await readInflight(phone);const reply=replyInflight(data);if(body._dry_run===true)return dryPayment(reply,data,'consulta_pagamento_cortex');const direct={...body,_direct_message:reply,_assinar_como:'joao',_source_tag:'joao_cortex_payment_read_v1'};delete direct._dry_run;return handler(new Request(req.url,{method:req.method,headers:req.headers,body:JSON.stringify(direct)}),info);}if(!paymentHistoryIntent(original))return handler(req,info);const data=await readPayment(phone,original);const reply=replyPayment(data,original);if(body._dry_run===true)return dryPayment(reply,data);const direct={...body,_direct_message:reply,_assinar_como:'joao',_source_tag:'joao_erp_payment_read_v1'};delete direct._dry_run;return handler(new Request(req.url,{method:req.method,headers:req.headers,body:JSON.stringify(direct)}),info);};return(previousServePayment as any)(...args);};
