import { AsyncLocalStorage } from 'node:async_hooks';

declare const Deno:any;

// João color-split request controller v1.2 — 12/09/2026
// Live: liga só quando há resposta curta a uma alternativa de cor dos últimos 30 min.
// Replay (_dry_run): janela 24h para reproduzir caso histórico.
// Força no MESMO round: calcular_rendimento_uv com quantidade corrigida + calcular_frete com CEP já conhecido.

const QRC_VERSION='joao-color-split-request-controller/v1.2';
const QRC_URL=(Deno.env.get('SUPABASE_URL')??'').replace(/\/$/,'');
const QRC_SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';
const qrcBaseFetch=globalThis.fetch.bind(globalThis);
const qrcNativeServe=Deno.serve.bind(Deno);
type QrcCtx={active:boolean;phone:string;leadId:string|null;targetTotal:number;distribution:string;colors:string[];cep:string;measure:{largura_cm:number;altura_cm:number};};
const qrcAls=new AsyncLocalStorage<QrcCtx>();
const COLOR_WORD='(branc[oa]s?|pret[oa]s?|dourad[oa]s?|pratead[oa]s?|azuis?|verdes?|vermelh[oa]s?|amarel[oa]s?|rosas?|rox[oa]s?|lil[aá]s|laranjas?|cinzas?|beges?)';
const COLOR_MAP:Array<[RegExp,string]>=[[/\bbranc[oa]s?\b/i,'branco'],[/\bpret[oa]s?\b/i,'preto'],[/\bdourad[oa]s?\b/i,'dourado'],[/\bpratead[oa]s?\b/i,'prateado'],[/\bazuis?\b/i,'azul'],[/\bverdes?\b/i,'verde'],[/\bvermelh[oa]s?\b/i,'vermelho'],[/\bamarel[oa]s?\b/i,'amarelo'],[/\brosas?\b/i,'rosa'],[/\brox[oa]s?\b/i,'roxo'],[/\blil[aá]s\b/i,'lilás'],[/\blaranjas?\b/i,'laranja'],[/\bcinzas?\b/i,'cinza'],[/\bbeges?\b/i,'bege']];
function u(input:RequestInfo|URL){return typeof input==='string'?input:input instanceof URL?input.href:input.url;}
async function raw(input:RequestInfo|URL,init?:RequestInit){if(typeof init?.body==='string')return init.body;if(init?.body!=null)return String(init.body);if(typeof Request!=='undefined'&&input instanceof Request){try{return await input.clone().text();}catch{}}return '';}
function json(body:any,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','x-cortex-color-split-request-controller':QRC_VERSION}});}
function canonColor(s:string){for(const[rx,c]of COLOR_MAP)if(rx.test(s))return c;return null;}
function countedColors(text:string){const rx=new RegExp(`\\b\\d{1,4}\\s+${COLOR_WORD}\\b`,'gi');const out:string[]=[];for(const m of String(text||'').matchAll(rx)){const c=canonColor(String(m[1]||''));if(c&&!out.includes(c))out.push(c);}return out;}
function isAmbiguous(text:string){return new RegExp(`^\\s*(?:seriam?|ser[aã]o|s[aã]o|ficariam?|ficam?)?\\s*\\d{1,4}\\s+${COLOR_WORD}\\s+ou\\s+\\d{1,4}\\s+de\\s+cada\\s+cor\\b[?.!\\s]*$`,'i').test(String(text||'').trim());}
function resolution(text:string):{mode:'each'|'single',n:number}|null{let m=String(text||'').trim().match(/^(?:quero\s+)?(\d{1,4})\s+de\s+cada\s+cor[?.!\s]*$/i);if(m)return{mode:'each',n:Number(m[1])};m=String(text||'').trim().match(/^(?:quero\s+)?(\d{1,4})\s+branc[oa]s?(?:\s+no\s+total)?[?.!\s]*$/i);if(m)return{mode:'single',n:Number(m[1])};return null;}
function measureFrom(text:string){const ms=[...String(text||'').matchAll(/\b(\d{1,3}(?:[.,]\d+)?)\s*x\s*(\d{1,3}(?:[.,]\d+)?)\s*cm\b/gi)];if(ms.length){const m=ms[ms.length-1],a=Number(m[1].replace(',','.')),b=Number(m[2].replace(',','.'));if(a>0&&b>0)return{largura_cm:a,altura_cm:b};}return null;}
function parseMaybe(v:any){for(let i=0;i<5;i++){if(typeof v!=='string')break;try{v=JSON.parse(v);}catch{break;}}return v;}
function toolUses(messages:any[]){const out:any[]=[];for(let i=0;i<(messages||[]).length;i++){const m=messages[i];if(m?.role!=='assistant'||!Array.isArray(m.content))continue;for(const b of m.content)if(b?.type==='tool_use')out.push({id:String(b.id||''),name:String(b.name||''),index:i});}return out;}
function allToolResultRaws(messages:any[]){const out:string[]=[];for(const m of messages||[]){if(m?.role!=='user'||!Array.isArray(m.content))continue;for(const b of m.content){if(b?.type!=='tool_result')continue;const c=b.content;if(typeof c==='string')out.push(c);else if(Array.isArray(c))out.push(c.filter((x:any)=>x?.type==='text').map((x:any)=>String(x?.text??'')).join(''));else{try{out.push(JSON.stringify(c));}catch{}}}}return out.filter(Boolean);}
function classifyResults(messages:any[]){let product:any=null,freight:any=null;for(const r of allToolResultRaws(messages)){const p=parseMaybe(r);const s=typeof p==='string'?p:JSON.stringify(p??{});if(!product&&(/quantidade_desejada|valor_por_adesivo|financial_authorizations/.test(s)&&/dtf_uv|adesivo_cm/.test(s)))product=p;if(!freight&&(/quote_snapshot_id|"opcoes"|J&T Standard|Sedex/.test(s)&&/frete|cep|opcoes/.test(s)))freight=p;}return{product,freight};}
function batchResponse(req:any,ctx:QrcCtx){const id1='toolu_'+crypto.randomUUID().replace(/-/g,''),id2='toolu_'+crypto.randomUUID().replace(/-/g,'');return json({id:'msg_'+crypto.randomUUID().replace(/-/g,''),type:'message',role:'assistant',model:req?.model||'controller',content:[{type:'tool_use',id:id1,name:'calcular_rendimento_uv',input:{largura_cm:ctx.measure.largura_cm,altura_cm:ctx.measure.altura_cm,quantidade_desejada:ctx.targetTotal}},{type:'tool_use',id:id2,name:'calcular_frete',input:{cep_destino:ctx.cep}}],stop_reason:'tool_use',stop_sequence:null,usage:{input_tokens:0,output_tokens:0}});}
function productAmount(p:any){const a=Array.isArray(p?.financial_authorizations)?p.financial_authorizations.find((x:any)=>x?.kind==='produto')?.amount:null;const n=Number(a);if(Number.isFinite(n)&&n>0)return n;const cents=Number(Array.isArray(p?.precos_verbalizaveis)?p.precos_verbalizaveis.find((x:any)=>x?.tipo==='preco_total')?.centavos:0);return cents>0?cents/100:null;}
function finalResponse(req:any,ctx:QrcCtx,p:any,f:any){const amount=productAmount(p);const fd=f?.display_data??f;const opcoes=Array.isArray(fd?.opcoes)?fd.opcoes:null;if(!amount||!opcoes?.length)return null;const opts=opcoes.map((o:any)=>`${o.servico}: ${o.preco??o.preco_formatado}, ${o.prazo??o.prazo_formatado}`).join(' | ');const msg=`Fechando em ${ctx.targetTotal} adesivos: DTF UV R$ ${amount.toFixed(2).replace('.',',')}. Frete para ${ctx.cep.slice(0,5)}-${ctx.cep.slice(5)}: ${opts}. Qual você prefere?`;const decision={responde:true,mensagem:msg,tema:'frete',encaminhou_venda:true,etapa:'fechamento',slots:{produto:'DTF UV',quantidade:`${ctx.targetTotal} adesivos (${ctx.distribution})`,cep:ctx.cep,envio_retirada:'envio',modalidade_logistica:'envio'}};return json({id:'msg_'+crypto.randomUUID().replace(/-/g,''),type:'message',role:'assistant',model:req?.model||'controller',content:[{type:'text',text:JSON.stringify(decision)}],stop_reason:'end_turn',stop_sequence:null,usage:{input_tokens:0,output_tokens:0}});}
async function readState(phone:string){try{const r=await qrcBaseFetch(`${QRC_URL}/rest/v1/agente_noturno_estado?select=lead_id,slots,updated_at&phone=eq.${encodeURIComponent(phone)}&order=updated_at.desc&limit=1`,{headers:{apikey:QRC_SERVICE,authorization:`Bearer ${QRC_SERVICE}`},signal:AbortSignal.timeout(1500)});if(!r.ok)return null;const rows=await r.json().catch(()=>[]);return Array.isArray(rows)?rows[0]??null:null;}catch{return null;}}
async function history(phone:string,ms:number){try{const suf=phone.replace(/\D/g,'').slice(-8),since=new Date(Date.now()-ms).toISOString();const r=await qrcBaseFetch(`${QRC_URL}/rest/v1/fact_conversations?select=direction,message_text,timestamp&phone=like.*${encodeURIComponent(suf)}&timestamp=gte.${encodeURIComponent(since)}&order=timestamp.desc&limit=80`,{headers:{apikey:QRC_SERVICE,authorization:`Bearer ${QRC_SERVICE}`},signal:AbortSignal.timeout(1800)});if(!r.ok)return[];const rows=await r.json().catch(()=>[]);return Array.isArray(rows)?rows:[];}catch{return[];}}
async function buildCtx(body:any):Promise<QrcCtx|null>{const phone=String(body?.phone??'').replace(/\D/g,''),msg=String(body?.mensagem??body?.message??'').trim(),res=resolution(msg);if(!phone||!res)return null;const replay=body?._dry_run===true;const[state,hist]=await Promise.all([readState(phone),history(phone,replay?86400000:1800000)]);const slots=state?.slots??{};if(!/dtf\s*uv/i.test(String(slots?.produto??'')))return null;if(!hist.some((r:any)=>r?.direction==='inbound'&&isAmbiguous(String(r?.message_text??''))))return null;const context=[String(slots?.quantidade??''),String(slots?.arte??''),...hist.map((r:any)=>String(r?.message_text??''))].join('\n'),colors=countedColors(context);if(colors.length<2)return null;const measure=measureFrom(String(slots?.arte??''))||measureFrom(context),cep=String(slots?.cep??'').replace(/\D/g,'');if(!measure||cep.length!==8)return null;const targetTotal=res.mode==='each'?res.n*colors.length:res.n,distribution=res.mode==='each'?colors.map(c=>`${res.n} ${c}`).join(', '):`${res.n} branco`;return{active:true,phone,leadId:state?.lead_id?String(state.lead_id):null,targetTotal,distribution,colors,cep,measure};}

globalThis.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const ctx=qrcAls.getStore(),url=u(input);if(!ctx?.active||!/^https:\/\/api\.anthropic\.com\/v1\/messages(?:\?|$)/i.test(url))return qrcBaseFetch(input,init);const bodyRaw=await raw(input,init);if(!bodyRaw)return qrcBaseFetch(input,init);let req:any;try{req=JSON.parse(bodyRaw);}catch{return qrcBaseFetch(input,init);}if(!Array.isArray(req?.messages)||req?.stream===true)return qrcBaseFetch(input,init);const us=toolUses(req.messages);if(!us.some(x=>x.name==='calcular_rendimento_uv')&&!us.some(x=>x.name==='calcular_frete'))return batchResponse(req,ctx);const {product,freight}=classifyResults(req.messages);if(product&&freight){const fin=finalResponse(req,ctx,product,freight);if(fin)return fin;}return qrcBaseFetch(input,init);};
(Deno as any).serve=(...args:any[])=>{const idx=typeof args[0]==='function'?0:1,handler=args[idx];if(typeof handler!=='function')throw new TypeError('Deno.serve handler missing');args[idx]=async(req:Request,info:any)=>{let ctx:QrcCtx|null=null;try{if(req.method==='POST'&&(req.headers.get('content-type')||'').toLowerCase().includes('application/json')){const body=await req.clone().json().catch(()=>null);if(body)ctx=await buildCtx(body);}}catch{}if(!ctx)return handler(req,info);console.log(JSON.stringify({event:'COLOR_SPLIT_REQUEST_CONTROLLER_ACTIVE',version:QRC_VERSION,target_total:ctx.targetTotal,colors:ctx.colors,cep:ctx.cep}));return qrcAls.run(ctx,()=>handler(req,info));};return qrcNativeServe(...args as any);};
